// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "e14a1615-3f0c-4997-a4bf-470a5ace5793";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onCurrentdistanceChange();
void onLedColorChange();
void onDetectThresholdChange();

float currentdistance;
CloudColoredLight ledColor;
int detectThreshold;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(currentdistance, READWRITE, ON_CHANGE, onCurrentdistanceChange);
  ArduinoCloud.addProperty(ledColor, READWRITE, ON_CHANGE, onLedColorChange);
  ArduinoCloud.addProperty(detectThreshold, READWRITE, ON_CHANGE, onDetectThresholdChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
